// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.AreaSettingPK;
import java.io.Serializable;

privileged aspect AreaSettingPK_Roo_Serializable {
    
    declare parents: AreaSettingPK implements Serializable;
    
    private static final long AreaSettingPK.serialVersionUID = 1L;
    
}
