// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.ContingentPK;
import java.io.Serializable;

privileged aspect ContingentPK_Roo_Serializable {
    
    declare parents: ContingentPK implements Serializable;
    
    private static final long ContingentPK.serialVersionUID = 1L;
    
}
