// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.DirectVoterPK;
import java.io.Serializable;

privileged aspect DirectVoterPK_Roo_Serializable {
    
    declare parents: DirectVoterPK implements Serializable;
    
    private static final long DirectVoterPK.serialVersionUID = 1L;
    
}
