// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.InterestPK;
import java.io.Serializable;

privileged aspect InterestPK_Roo_Serializable {
    
    declare parents: InterestPK implements Serializable;
    
    private static final long InterestPK.serialVersionUID = 1L;
    
}
