// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.IssueSettingPK;
import java.io.Serializable;

privileged aspect IssueSettingPK_Roo_Serializable {
    
    declare parents: IssueSettingPK implements Serializable;
    
    private static final long IssueSettingPK.serialVersionUID = 1L;
    
}
