// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.MemberImagePK;
import java.io.Serializable;

privileged aspect MemberImagePK_Roo_Serializable {
    
    declare parents: MemberImagePK implements Serializable;
    
    private static final long MemberImagePK.serialVersionUID = 1L;
    
}
