// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.PrivilegePK;
import java.io.Serializable;

privileged aspect PrivilegePK_Roo_Serializable {
    
    declare parents: PrivilegePK implements Serializable;
    
    private static final long PrivilegePK.serialVersionUID = 1L;
    
}
