// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.RenderedMemberStatement;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RenderedMemberStatement_Roo_Configurable {
    
    declare @type: RenderedMemberStatement: @Configurable;
    
}
