// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.RenderedDraftPK;
import java.io.Serializable;

privileged aspect RenderedDraftPK_Roo_Serializable {
    
    declare parents: RenderedDraftPK implements Serializable;
    
    private static final long RenderedDraftPK.serialVersionUID = 1L;
    
}
