// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.computerlyrik.lf.webapp;

import de.computerlyrik.lf.webapp.SupporterPK;
import java.io.Serializable;

privileged aspect SupporterPK_Roo_Serializable {
    
    declare parents: SupporterPK implements Serializable;
    
    private static final long SupporterPK.serialVersionUID = 1L;
    
}
